name: sahifaty

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  fl_chart: ^1.1.1
  pie_chart_3d: ^0.0.7
  dropdown_button2: ^2.3.9
  quran: ^1.3.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  fluttertoast: ^9.0.0
  http: ^1.5.0
  connectivity_plus: ^7.0.0
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2
  flutter_svg: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/clean_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/json/data.json
    - assets/json/intl_ar.json
    - assets/json/intl_en.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri.ttf
